<template><h1 id="other-packages" tabindex="-1"><a class="header-anchor" href="#other-packages" aria-hidden="true">#</a> Other Packages</h1>
<p>While we think you can get pretty darn far in R with just <strong>data.table</strong> and
<strong>fixest</strong>, of course those two don't cover everything.</p>
<p>This page covers a small list of packages you may find especially useful when
getting started with R. We won't try to cover everything under the sun here.
Just a few places to get going. For the rest, well, that's what Google is for
(or, indeed, to learn about each of these in more detail).</p>
<p>All of the below packages have far more applications than is shown here. We'll
just provide one or two examples of how each can be used. Finally, don't forget
to install them with <code>install.packages('PKGNAME')</code> and load them with
<code>library(PKGNAME)</code>. The former command you only have to run once per package (or
as often as you want to update it); the latter whenever you want to use a
package in a new R session.</p>
<h2 id="ggplot2-beautiful-and-customizable-plots" tabindex="-1"><a class="header-anchor" href="#ggplot2-beautiful-and-customizable-plots" aria-hidden="true">#</a> ggplot2: Beautiful and customizable plots</h2>
<p><a href="https://ggplot2.tidyverse.org/" target="_blank" rel="noopener noreferrer"><strong>ggplot2</strong><ExternalLinkIcon/></a> is widely considered one of the
preeminent plotting libraries available in any language. It provides an
intuitive syntax that applies in the same way across many, many different kinds
of vizualisations, and with a deep level of customization. Plus, endless
additional plugins to do what you want, including easy interactivity, animation,
maps, etc. We thought about giving <strong>ggplot2</strong> its own dedicated page like
<strong>data.table</strong> and <strong>fixest</strong>. But instead we'll point you to the
<a href="https://lost-stats.github.io/Presentation/Figures/Figures.html" target="_blank" rel="noopener noreferrer">Figures<ExternalLinkIcon/></a>
section of the <em>Library of Statistical Techniques</em>, which already shows how to
do many different graphing tasks in both Stata and <strong>ggplot2</strong>. For a more
in-depth overview you can always consult the excellent
<a href="https://ggplot2.tidyverse.org/" target="_blank" rel="noopener noreferrer">package documentation<ExternalLinkIcon/></a>, or a book like Kieran
Healy's wonderful <a href="https://socviz.co/" target="_blank" rel="noopener noreferrer"><em>Data Visualization</em><ExternalLinkIcon/></a>.</p>
<h3 id="basic-scatterplot" tabindex="-1"><a class="header-anchor" href="#basic-scatterplot" aria-hidden="true">#</a> Basic scatterplot</h3>
<div class="code--container">
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">twoway</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">scatter</span><span style="color: var(--shiki-color-text)"> yvar xvar</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">twoway</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">(scatter</span><span style="color: var(--shiki-color-text)"> yvar xvar </span><span style="color: var(--shiki-token-keyword)">if</span><span style="color: var(--shiki-color-text)"> group </span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">1</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-function)">mc</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">blue</span><span style="color: var(--shiki-color-text)">)</span><span style="color: var(--shiki-token-keyword)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">\\</span><span style="color: var(--shiki-color-text)">\</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-keyword)">(scatter</span><span style="color: var(--shiki-color-text)"> yvar xvar </span><span style="color: var(--shiki-token-keyword)">if</span><span style="color: var(--shiki-color-text)"> group </span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">2</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-function)">mc</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">red</span><span style="color: var(--shiki-color-text)">)</span><span style="color: var(--shiki-token-keyword)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-function)">ggplot(</span><span style="color: var(--shiki-token-punctuation)">dat, </span><span style="color: var(--shiki-token-function)">aes(</span><span style="color: var(--shiki-token-punctuation)">x </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> xvar, y </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> yvar</span><span style="color: var(--shiki-token-function)">))</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">geom_point()</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">ggplot(</span><span style="color: var(--shiki-token-punctuation)">dat, </span><span style="color: var(--shiki-token-function)">aes(</span><span style="color: var(--shiki-token-punctuation)">x </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> xvar, y </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> yvar, color </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> group</span><span style="color: var(--shiki-token-function)">))</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">  </span><span style="color: var(--shiki-token-function)">geom_point()</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
</div>
<h2 id="tidyverse" tabindex="-1"><a class="header-anchor" href="#tidyverse" aria-hidden="true">#</a> tidyverse</h2>
<p>The <a href="https://www.tidyverse.org/" target="_blank" rel="noopener noreferrer"><strong>tidyverse</strong><ExternalLinkIcon/></a> provides an extremely popular
framework for data science tasks in R. This meta-package is actually a
collection of smaller packages that are all designed to work together, based on
a shared philosophy and syntax. We've already covered <strong>ggplot2</strong> above, but
there are plenty more. These include <strong>dplyr</strong> and <strong>tidyr</strong>, which offer an
alternative syntax and approach to data wrangling tasks. While we personally
recommend <strong>data.table</strong>, these <strong>tidyverse</strong> packages have many ardent fans
too. You may find that you prefer their modular design and verbal syntax. But
don't feel bound either way: it's totally fine to combine them. Some other
<strong>tidyverse</strong> packages worth knowing about include <strong>purrr</strong>, which contains a suite
of functions for automating and looping your work, <strong>lubridate</strong> which makes
working with date-based data easy, and <strong>stringr</strong> which offers functions with
straightforward syntax for working with string variables.</p>
<h3 id="data-wrangling-with-dplyr" tabindex="-1"><a class="header-anchor" href="#data-wrangling-with-dplyr" aria-hidden="true">#</a> Data wrangling with dplyr</h3>
<p><em>Note: <strong>dplyr</strong> doesn't modify data in place. So you'll need to (re)assign if you want to keep your changes. E.g. <code>dat = dat %&gt;% group_by...</code></em></p>
<div class="code--container">
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* Subset by rows and then columns</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">keep</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">if</span><span style="color: var(--shiki-color-text)"> var1</span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-token-string-expression)">&quot;value&quot;</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">keep</span><span style="color: var(--shiki-color-text)"> var1 var2 var3</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* Create a new variable by group</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">bysort</span><span style="color: var(--shiki-color-text)"> group1</span><span style="color: var(--shiki-token-keyword)">:</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">egen</span><span style="color: var(--shiki-color-text)"> mean_var1 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">mean</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">var1</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* Collapse by group</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">collapse</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">(mean)</span><span style="color: var(--shiki-color-text)"> arr_delay, </span><span style="color: var(--shiki-token-function)">by</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">carrier</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># Subset by rows and then columns</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">dat </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span><span style="color: var(--shiki-color-text)">   </span><span style="color: var(--shiki-token-comment)"># `%&gt;%` is the tidyverse &quot;pipe&quot; operator</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">   </span><span style="color: var(--shiki-token-function)">filter</span><span style="color: var(--shiki-color-text)">(var1</span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-token-string-expression)">&quot;value&quot;</span><span style="color: var(--shiki-color-text)">) </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">   </span><span style="color: var(--shiki-token-function)">select(</span><span style="color: var(--shiki-token-punctuation)">var1, var2, var3</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Create a new variable by group</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">dat </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">  </span><span style="color: var(--shiki-token-function)">group_by(</span><span style="color: var(--shiki-token-punctuation)">group1</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">  </span><span style="color: var(--shiki-token-function)">mutate(</span><span style="color: var(--shiki-token-punctuation)">mean_var1 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> </span><span style="color: var(--shiki-token-function)">mean</span><span style="color: var(--shiki-token-punctuation)">(var1</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Collapse by group</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">dat </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">  </span><span style="color: var(--shiki-token-function)">group_by(</span><span style="color: var(--shiki-token-punctuation)">group1</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">  </span><span style="color: var(--shiki-token-function)">summarise(</span><span style="color: var(--shiki-token-punctuation)">mean_var1 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> </span><span style="color: var(--shiki-token-function)">mean</span><span style="color: var(--shiki-token-punctuation)">(var1</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div></div>
</div>
<h3 id="manipulating-dates-with-lubridate" tabindex="-1"><a class="header-anchor" href="#manipulating-dates-with-lubridate" aria-hidden="true">#</a> Manipulating dates with lubridate</h3>
<div class="code--container">
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* Shift a date forward one month (not 30 days, one month)</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* ???</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># Shift a date forward one month (not 30 days, one month)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">shifted_date </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> date </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">months</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-constant)">1</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
</div>
<h3 id="iterating-with-purrr" tabindex="-1"><a class="header-anchor" href="#iterating-with-purrr" aria-hidden="true">#</a> Iterating with purrr</h3>
<div class="code--container">
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* Read in many files and append them together</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">local</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">filelist</span><span style="color: var(--shiki-token-keyword)">:</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">dir</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&quot;Data/&quot;</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">files</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&quot;*.dta&quot;</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">local</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">firsttime</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">1</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">foreach</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">f</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">in</span><span style="color: var(--shiki-color-text)"> filelist </span><span style="color: var(--shiki-token-keyword)">{</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">use</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-color-text)">`</span><span style="color: var(--shiki-token-function)">f</span><span style="color: var(--shiki-color-text)">&#39;</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-keyword)">clear</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">if</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-color-text)">`</span><span style="color: var(--shiki-token-function)">firsttime</span><span style="color: var(--shiki-color-text)">&#39;</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">0</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">{</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-keyword)">append</span><span style="color: var(--shiki-color-text)"> using compiled_data.dta</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">}</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">save</span><span style="color: var(--shiki-color-text)"> compiled_data.dta, replace</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># Read in many files and append them together</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># (this combines purrr with the data.table function fread)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">filelist </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">list.files</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;Data/&#39;</span><span style="color: var(--shiki-color-text)">, pattern </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&#39;.csv&#39;</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">dat </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> filelist </span><span style="color: var(--shiki-token-keyword)">%&gt;%</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-function)">map_df(</span><span style="color: var(--shiki-token-punctuation)">fread</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div></div>
</div>
<h3 id="string-operations-with-stringr" tabindex="-1"><a class="header-anchor" href="#string-operations-with-stringr" aria-hidden="true">#</a> String operations with stringr</h3>
<div class="code--container">
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-function)">subinstr</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">string</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-string-expression)">&quot;remove&quot;</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-string-expression)">&quot;replace&quot;</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-constant)">.</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">substr</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">string</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-parameter)">start</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-parameter)">length</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">regex</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">string</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-string-expression)">&quot;regex&quot;</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-function)">str_replace_all(</span><span style="color: var(--shiki-token-punctuation)">string, </span><span style="color: var(--shiki-token-string-expression)">&quot;remove&quot;</span><span style="color: var(--shiki-token-punctuation)">, </span><span style="color: var(--shiki-token-string-expression)">&quot;replace&quot;</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">str_sub(</span><span style="color: var(--shiki-token-punctuation)">string, start, end</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">str_detect(</span><span style="color: var(--shiki-token-punctuation)">string, </span><span style="color: var(--shiki-token-string-expression)">&quot;regex&quot;</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Note all the stringr functions accept regex input</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div></div>
</div>
<h2 id="collapse-extra-convenience-functions-and-super-fast-aggregations" tabindex="-1"><a class="header-anchor" href="#collapse-extra-convenience-functions-and-super-fast-aggregations" aria-hidden="true">#</a> collapse: Extra convenience functions and super fast aggregations</h2>
<p>p&gt;Sure, we've gone on and on about how fast <code>data.table</code> is compared to just about everything else. But there is another R package that can boast even faster computation times for certain grouped calculations and transformations, and that's <a href = "https://sebkrantz.github.io/collapse/index.html" >collapse</a>. The <code>collapse</code> package doesn't try to do everything that <code>data.table</code> does. But the two <a href="https://sebkrantz.github.io/collapse/articles/collapse_and_data.table.html">play very well together</a> and the former offers some convenience functions like <code>descr</code> and <code>collap</code>, which essentially mimic the equivalent functions in Stata and might be particularly appealing to readers of this guide. (P.S. If you'd like to load <code>data.table</code> and <code>collapse</code> at the same time, plus some other high-performance packages, check out the <a href = "https://sebkrantz.github.io/fastverse/index.html" >fastverse</a>.)</p>
<h3 id="quick-summaries" tabindex="-1"><a class="header-anchor" href="#quick-summaries" aria-hidden="true">#</a> Quick Summaries</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">summarize</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">describe</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-function)">qsu(</span><span style="color: var(--shiki-token-punctuation)">dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">descr(</span><span style="color: var(--shiki-token-punctuation)">dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
</div>
<h3 id="multiple-grouped-aggregations" tabindex="-1"><a class="header-anchor" href="#multiple-grouped-aggregations" aria-hidden="true">#</a> Multiple grouped aggregations</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">collapse</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">(mean)</span><span style="color: var(--shiki-color-text)"> var1, </span><span style="color: var(--shiki-token-function)">by</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">group1</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">collapse</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">(</span><span style="color: var(--shiki-color-text)">min</span><span style="color: var(--shiki-token-keyword)">)</span><span style="color: var(--shiki-color-text)"> min_var1</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)">var1 min_var2</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)">var2 </span><span style="color: var(--shiki-token-keyword)">(</span><span style="color: var(--shiki-color-text)">max</span><span style="color: var(--shiki-token-keyword)">)</span><span style="color: var(--shiki-color-text)"> max_var1</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)">var1 max_var2</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)">var2, </span><span style="color: var(--shiki-token-function)">by</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">group1</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-parameter)">group2</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-function)">collap(</span><span style="color: var(--shiki-token-punctuation)">dat, var1 </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> group1, fmean</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-comment)"># &#39;fmean&#39; =&gt; fast mean</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">collap(</span><span style="color: var(--shiki-token-punctuation)">dat, var1 </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> var2 </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> group1 </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> group2, FUN </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> </span><span style="color: var(--shiki-token-keyword)">list</span><span style="color: var(--shiki-token-punctuation)">(fmin, fmax)</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
</div>
<h2 id="sandwich-more-standard-error-adjustments" tabindex="-1"><a class="header-anchor" href="#sandwich-more-standard-error-adjustments" aria-hidden="true">#</a> sandwich: More Standard Error Adjustments</h2>
<p>The <code>fixest</code> package comes with plenty of shortcuts for accessing standard-error adjustments like HC1 heteroskedasticity-robust standard errors, Newey-West, Driscoll-Kraay, or clustered standard errors. But there is, of course, more than that! Many additional options are covered by the <code>sandwich</code> package, which comes with a long list of functions like <code>vcovBS()</code> for bootstrapped standard errors, or <code>vcovHAC()</code> for HAC. These can slot right into <code>fixest</code> estimates, too! You shouldn't be using those &quot;, robust&quot; errors for smaller samples anyway... but you <a href = "http://datacolada.org/99">knew that</a>, right?</p>
<h3 id="linear-model-adjustments" tabindex="-1"><a class="header-anchor" href="#linear-model-adjustments" aria-hidden="true">#</a> Linear Model Adjustments</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* &quot;, robust&quot; uses hc1 which isn&#39;t great for small samples</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">regress</span><span style="color: var(--shiki-color-text)"> Y X Z, </span><span style="color: var(--shiki-token-function)">vce</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">hc3</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># sandwich&#39;s vcovHC uses HC3 by default</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">feols(</span><span style="color: var(--shiki-token-punctuation)">Y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> X </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> Z, dat,vcov </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> sandwich</span><span style="color: var(--shiki-token-keyword)">::</span><span style="color: var(--shiki-token-punctuation)">vcovHC</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Aside: Remember that you can also adjust the SEs </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># for existing models on the fly </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">m </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">feols(</span><span style="color: var(--shiki-token-punctuation)">Y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> X </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> Z, dat</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">summary</span><span style="color: var(--shiki-color-text)">(m, vcov </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> sandwich</span><span style="color: var(--shiki-token-keyword)">::</span><span style="color: var(--shiki-color-text)">vcovHC)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div></div>
</div>
<h2 id="modelsummary-summary-tables-regression-tables-and-more" tabindex="-1"><a class="header-anchor" href="#modelsummary-summary-tables-regression-tables-and-more" aria-hidden="true">#</a> modelsummary: Summary tables, regression tables, and more</h2>
<p>The <code>fixest</code> package already has the <code>etable()</code> function for generating regression tables. However, it is only really intended to work with models from the same package. So we also recommend checking out the fantastic <a href = "https://vincentarelbundock.github.io/modelsummary/">modelsummary</a> package. It works with all sorts of model objects, including those not from <code>fixest</code>, is incredibly customizable, and outputs to a bunch of different formats (PDF, HTML, DOCX, etc). Similarly, <code>modelsummary</code> has a wealth of options for producing publication-ready summary tables. Oh, and it produces coefficient plots too. Check out the <a href = "https://vincentarelbundock.github.io/modelsummary/">package website</a> for more.</p>
<h3 id="summary-table" tabindex="-1"><a class="header-anchor" href="#summary-table" aria-hidden="true">#</a> Summary Table</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* Summary stats table </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">estpost</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">summarize</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-function)">cells</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&quot;count mean sd min max&quot;</span><span style="color: var(--shiki-color-text)">) nomtitle nonumber </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* Balance table </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">by</span><span style="color: var(--shiki-color-text)"> treat_var</span><span style="color: var(--shiki-token-keyword)">:</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">eststo:</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">estpost</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">summarize</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)">, </span><span style="color: var(--shiki-token-function)">cells</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&quot;mean sd&quot;</span><span style="color: var(--shiki-color-text)">) label nodepvar</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># Summary stats table </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">datasummary_skim(</span><span style="color: var(--shiki-token-punctuation)">dat</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Balance table </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">datasummary_balance(</span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)">treat_var, dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div></div>
</div>
<h3 id="regression-table" tabindex="-1"><a class="header-anchor" href="#regression-table" aria-hidden="true">#</a> Regression Table</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">reg</span><span style="color: var(--shiki-color-text)"> Y X Z </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">eststo</span><span style="color: var(--shiki-color-text)"> est1 </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)"> est1b</span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">reg</span><span style="color: var(--shiki-color-text)"> Y X Z, </span><span style="color: var(--shiki-token-function)">vce</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">hc3</span><span style="color: var(--shiki-color-text)">) </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">eststo</span><span style="color: var(--shiki-color-text)"> est1b </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)"> est1b </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)"> est1 est1b</span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">reg</span><span style="color: var(--shiki-color-text)"> Y X Z A, </span><span style="color: var(--shiki-token-function)">vce</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">hc3</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">eststo</span><span style="color: var(--shiki-color-text)"> est2</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">esttab</span><span style="color: var(--shiki-color-text)"> est1 est1b est2</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-color-text)">est1 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">lm</span><span style="color: var(--shiki-color-text)">(Y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-color-text)"> X </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> Z, dat) </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">msummary(</span><span style="color: var(--shiki-token-punctuation)">est1</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-comment)"># msummary() = alias for modelsummary()</span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Like fixest::etable(), SEs for existing models can</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># be adjusted on-the-fly </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">msummary(</span><span style="color: var(--shiki-token-punctuation)">est1, vcov</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-string-expression)">&#39;HC3&#39;</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Multiple SEs for the same model</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">msummary(</span><span style="color: var(--shiki-token-punctuation)">est1, vcov</span><span style="color: var(--shiki-token-keyword)">=list</span><span style="color: var(--shiki-token-punctuation)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;iid&#39;</span><span style="color: var(--shiki-token-punctuation)">, </span><span style="color: var(--shiki-token-string-expression)">&#39;HC3&#39;</span><span style="color: var(--shiki-token-punctuation)">)</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-color-text)">est3 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">lm</span><span style="color: var(--shiki-color-text)">(Y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-color-text)"> X </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> Z </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> A, dat) </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">msummary(</span><span style="color: var(--shiki-token-keyword)">list</span><span style="color: var(--shiki-token-punctuation)">(est1, est1, est3),</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">         vcov </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> </span><span style="color: var(--shiki-token-keyword)">list</span><span style="color: var(--shiki-token-punctuation)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;iid&#39;</span><span style="color: var(--shiki-token-punctuation)">, </span><span style="color: var(--shiki-token-string-expression)">&#39;HC3&#39;</span><span style="color: var(--shiki-token-punctuation)">, </span><span style="color: var(--shiki-token-string-expression)">&#39;HC3&#39;</span><span style="color: var(--shiki-token-punctuation)">)</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div></div>
</div>
<h2 id="lme4-random-effects-and-mixed-models" tabindex="-1"><a class="header-anchor" href="#lme4-random-effects-and-mixed-models" aria-hidden="true">#</a> lme4: Random effects and mixed models</h2>
<p><code>fixest</code> can do a lot, but it can't do everything. This site isn't even going to attempt to go into how to translate every single model into R. But we'll quick highlight random-effects and mixed models. The <a href = "https://cran.r-project.org/web/packages/lme4/index.html">lme4</a> package and its <code>lmer()</code> function covers not just random-intercept models but also hierarchical models where slope coefficients follow random distributions. (<strong>Aside:</strong> If you prefer Bayesian models for this kind of thing, check out the <a href = "https://paul-buerkner.github.io/brms/">brms</a> package.)</p>
<h3 id="random-effects-and-mixed-models" tabindex="-1"><a class="header-anchor" href="#random-effects-and-mixed-models" aria-hidden="true">#</a> Random Effects and Mixed Models</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">xtset</span><span style="color: var(--shiki-color-text)"> group time</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">xtreg</span><span style="color: var(--shiki-color-text)"> Y X, re</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">mixed lifeexp </span><span style="color: var(--shiki-token-keyword)">||</span><span style="color: var(--shiki-color-text)"> countryn</span><span style="color: var(--shiki-token-keyword)">:</span><span style="color: var(--shiki-color-text)"> gdppercap</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># No need for an xtset equivalent</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">m </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">lmer(</span><span style="color: var(--shiki-token-punctuation)">Y</span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)">(</span><span style="color: var(--shiki-token-constant)">1</span><span style="color: var(--shiki-token-keyword)">|</span><span style="color: var(--shiki-token-punctuation)">group) </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> X, data </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">nm </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">lmer(</span><span style="color: var(--shiki-token-punctuation)">Y</span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)">(</span><span style="color: var(--shiki-token-constant)">1</span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)">x</span><span style="color: var(--shiki-token-keyword)">|</span><span style="color: var(--shiki-token-punctuation)">group) </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> X, data </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
</div>
<h2 id="marginaleffects-marginal-effects-constrasts-etc" tabindex="-1"><a class="header-anchor" href="#marginaleffects-marginal-effects-constrasts-etc" aria-hidden="true">#</a> marginaleffects: Marginal effects, constrasts, etc.</h2>
<p>The Stata <code>margins</code> command is great. To replicate it in R, we recommend the <a href = "https://vincentarelbundock.github.io/marginaleffects/">marginaleffects</a> package. Individual marginal effects or average marginal effects for nonlinear models, or models with interactions or transformations, etc. It's also very fast.</p>
<h3 id="basic-logit-marginal-effects" tabindex="-1"><a class="header-anchor" href="#basic-logit-marginal-effects" aria-hidden="true">#</a> Basic Logit Marginal Effects</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* A logit:</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">logit</span><span style="color: var(--shiki-color-text)"> Y X Z</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">margins, </span><span style="color: var(--shiki-token-function)">dydx</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-keyword)">*</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># This example incorporates the fixest function feglm()</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">m </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">feglm(</span><span style="color: var(--shiki-token-punctuation)">Y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> X </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> Z, family </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> binomial, data </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> mtcars</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">summary</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-function)">marginaleffects(</span><span style="color: var(--shiki-token-punctuation)">m</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></div>
</div>
<h2 id="multcomp-and-nlwaldtest-joint-coefficient-tests" tabindex="-1"><a class="header-anchor" href="#multcomp-and-nlwaldtest-joint-coefficient-tests" aria-hidden="true">#</a> multcomp and nlWaldTest: Joint coefficient tests</h2>
<p>Stata provides a number of inbuilt commands for (potentially complex) postestimation coefficient tests like <code>testparm</code>, <code>lincom</code>, and <code>nlcom</code>. We've already seen that <code>fixest</code> covers the <code>testparm</code> equivalent with its <code>wald()</code> function. But what about combinations of coefficients? The <a href = "http://multcomp.r-forge.r-project.org/">multcomp</a> package handles a variety of linear tests and combinations, while <a href = "https://cran.r-project.org/web/packages/nlWaldTest/index.html">nlWaldTest</a> has you covered for nonlinear combinations.</p>
<h3 id="test-other-null-hypotheses-and-coefficient-combinations" tabindex="-1"><a class="header-anchor" href="#test-other-null-hypotheses-and-coefficient-combinations" aria-hidden="true">#</a> Test other null hypotheses and coefficient combinations</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-keyword)">regress</span><span style="color: var(--shiki-color-text)"> y x z </span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* One-sided test </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">test</span><span style="color: var(--shiki-color-text)"> _b[x]</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-constant)">0</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">local</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">sign_wgt</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">sign</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">_b</span><span style="color: var(--shiki-color-text)">[x]) </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">display</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&quot;H0: coef &amp;lt;= 0  p-value = &quot;</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">ttail</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">r</span><span style="color: var(--shiki-token-keyword)">(</span><span style="color: var(--shiki-token-parameter)">df_r</span><span style="color: var(--shiki-token-keyword)">)</span><span style="color: var(--shiki-color-text)">,</span><span style="color: var(--shiki-color-text)">`</span><span style="color: var(--shiki-token-function)">sign_wgt</span><span style="color: var(--shiki-color-text)">&#39;</span><span style="color: var(--shiki-token-keyword)">*</span><span style="color: var(--shiki-token-parameter)">sqrt</span><span style="color: var(--shiki-token-keyword)">(</span><span style="color: var(--shiki-token-function)">r</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-parameter)">F</span><span style="color: var(--shiki-color-text)">)</span><span style="color: var(--shiki-token-keyword)">)</span><span style="color: var(--shiki-color-text)">) </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* Test linear combination of coefficients </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">lincom</span><span style="color: var(--shiki-color-text)"> x </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> z </span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* Test nonlinear combination of coefficients </span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">nlcom</span><span style="color: var(--shiki-color-text)"> _b[x]/_b[z]</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-color-text)">m </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">feols(</span><span style="color: var(--shiki-token-punctuation)">y </span><span style="color: var(--shiki-token-keyword)">~</span><span style="color: var(--shiki-token-punctuation)"> x </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-token-punctuation)"> z, dat</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Note: we recommend the dev version of multcomp </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># install.packages(&quot;multcomp&quot;, repos=&quot;http://R-Forge.R-project.org&quot;) </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># One-sided test </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">m2 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> multcomp</span><span style="color: var(--shiki-token-keyword)">::</span><span style="color: var(--shiki-token-function)">ghlt(</span><span style="color: var(--shiki-token-punctuation)">m, </span><span style="color: var(--shiki-token-string-expression)">&#39;x&amp;lt;=0&#39;</span><span style="color: var(--shiki-token-function)">)</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">summary</span><span style="color: var(--shiki-color-text)">(m2) </span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Test linear combination of coefficients </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">m3 </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> multcomp</span><span style="color: var(--shiki-token-keyword)">::</span><span style="color: var(--shiki-token-function)">glht(</span><span style="color: var(--shiki-token-punctuation)">m, </span><span style="color: var(--shiki-token-string-expression)">&#39;x + z = 0&#39;</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">summary</span><span style="color: var(--shiki-color-text)">(m3) </span><span style="color: var(--shiki-token-comment)"># or confint(m3) </span></span>
<span class="line"></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Test nonlinear combination of coefficients </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">nlWaldtest</span><span style="color: var(--shiki-token-keyword)">::</span><span style="color: var(--shiki-token-function)">nlWaldtest(</span><span style="color: var(--shiki-token-punctuation)">m, </span><span style="color: var(--shiki-token-string-expression)">&#39;b[2]/b[3]&#39;</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-comment)"># or nlWaldtest::nlConfint()</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div></div>
</div>
<h2 id="sf-geospatial-operations" tabindex="-1"><a class="header-anchor" href="#sf-geospatial-operations" aria-hidden="true">#</a> sf: Geospatial operations</h2>
<p>R has outstanding support for geospatial computation and mapping. There are a variety of packages to choose from here, depending on what you want (e.g. interactive maps, high-dimensional data cubes, etc.) But the workhorse geospatial tool for most R users is the incredibly versatile <a href = "https://r-spatial.github.io/sf/">sf</a> package. We'll only provide a simple mapping example below. The <code>sf</code> <a href = "https://r-spatial.github.io/sf/">website</a> has several in-depth tutorials, and we also recommend the <a href = "https://geocompr.robinlovelace.net/">Geocomputation with R</a> book by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow.</p>
<h3 id="simple-map" tabindex="-1"><a class="header-anchor" href="#simple-map" aria-hidden="true">#</a> Simple Map</h3>
<div class='code--container'>
<div>
<div class="language-stata ext-stata line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">* Mapping in Stata requires the spmap and shp2dta </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* commands, and also that you convert your (say) </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* shapefile to .dta format first. We won&#39;t go through </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* all that here, but see: </span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">* https://www.stata.com/support/faqs/graphics/spmap-and-maps/</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div></div>
<div>
<div class="language-r ext-r line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)"># This example uses the North Carolina shapefile that is</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># bundled with the sf package. </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">nc </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">st_read(system.file</span><span style="color: var(--shiki-token-punctuation)">(</span><span style="color: var(--shiki-token-string-expression)">&quot;shape/nc.shp&quot;</span><span style="color: var(--shiki-token-punctuation)">, package </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)"> </span><span style="color: var(--shiki-token-string-expression)">&quot;sf&quot;</span><span style="color: var(--shiki-token-function)">)</span><span style="color: var(--shiki-color-text)">) </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">plot</span><span style="color: var(--shiki-color-text)">(nc[, </span><span style="color: var(--shiki-token-string-expression)">&#39;BIR74&#39;</span><span style="color: var(--shiki-color-text)">])</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)"># Or, if you have ggplot2 loaded: </span></span>
<span class="line"><span style="color: var(--shiki-token-function)">ggplot(</span><span style="color: var(--shiki-token-punctuation)">nc, </span><span style="color: var(--shiki-token-function)">aes(</span><span style="color: var(--shiki-token-punctuation)">fill</span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-token-punctuation)">BIR74</span><span style="color: var(--shiki-token-function)">))</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">geom_sf()</span></span>
<span class="line"></span></code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div></div>
</div>
</template>
